package com.nxp.iemdm.enums.configuration;

import lombok.Getter;

@Getter
public enum ConfigurationValueType {
  DATABASE("DATABASE"),
  I2_VERSION("I2-version"),
  MAX_NOTIFICATIONS("MaxNotifications"),
  DEBOUNCE_TIME("DebounceTime"),
  DEFAULT_EC_AVAILABILITY("DEFAULT_EC_AVAILABILITY"),
  DEFAULT_EC_OPERATION_UTILIZATION_PK("DEFAULT_EC_OPERATION_UTILIZATION_PK"),
  DEFAULT_EC_MAN_MACHINE_RATIO_PK("DEFAULT_EC_MAN_MACHINE_RATIO_PK"),
  DEFAULT_EC_POV_EFFICIENCY_PK("DEFAULT_EC_POV_EFFICIENCY_PK"),
  DEFAULT_EC_PKUT_PK("DEFAULT_EC_PKUT_PK"),
  DEFAULT_EC_INDEXTIME_FT("DEFAULT_EC_INDEXTIME_FT"),
  DEFAULT_EC_INDEXTIME_WT("DEFAULT_EC_INDEXTIME_WT"),
  DEFAULT_EC_LOADTIME_FT("DEFAULT_EC_LOADTIME_FT"),
  DEFAULT_EC_LOADTIME_WT("DEFAULT_EC_LOADTIME_WT"),
  DEFAULT_PRODUCTPERFORMANCE_FT("DEFAULT_PRODUCTPERFORMANCE_FT"),
  DEFAULT_PRODUCTPERFORMANCE_WT("DEFAULT_PRODUCTPERFORMANCE_WT"),
  DEFAULT_UR_FINANCIAL_COLD_ADDER_FT("DEFAULT_UR_FINANCIAL_COLD_ADDER_FT"),
  DEFAULT_UR_FINANCIAL_COLD_ADDER_WT("DEFAULT_UR_FINANCIAL_COLD_ADDER_WT"),
  DEFAULT_BI_AVAILABILITY("DEFAULT_BI_AVAILABILITY"),
  DEFAULT_BI_RE_BI_RATE("DEFAULT_BI_RE_BI_RATE"),
  DEFAULT_BI_SOCKET_UTILIZATION("DEFAULT_BI_SOCKET_UTILIZATION"),
  DEFAULT_BI_SLOTS_PER_CHAMBER("DEFAULT_BI_SLOTS_PER_CHAMBER"),
  DEFAULT_BI_CHAMBER_ADJ_FACTOR("DEFAULT_BI_CHAMBER_ADJ_FACTOR"),
  DEFAULT_BI_TIME_BETWEEN_TURNS("DEFAULT_BI_TIME_BETWEEN_TURNS"),
  UR_MAX_PRIO_DCM("UR_MAX_PRIO_DCM"),
  UR_MAX_PRIO_JDA("UR_MAX_PRIO_JDA"),
  READ_ONLY_MODE("READ_ONLY_MODE");

  private final String configItem;

  ConfigurationValueType(String configItem) {
    this.configItem = configItem;
  }
}
