package com.nxp.iemdm.model.search;

/**
 * This enum is used in GenericSearch in order to dynamically filter and sort on any entity. The
 * enum have a prefix (like P_ for Part12Nc) with all the possible field which can filtered and
 * sorted. The frontend only has to set the correct enum value. The enum has the corresponding field
 * name which may nested like "location.acronym". In that the case the property cachedResources may
 * be used to filter/sort using the corresponding cached entity so the query can be lazy.
 */
public enum GenericSearchSortField {

  // @see NC12SitePart
  P_PART12NC("part12Nc"),
  P_ACRONYM("acronym"),
  P_SITE("plantCode"),
  P_DESCRIPTION("partDescription"),
  P_TYPE("type"),
  P_TYPEGROUP("typeGroup"),
  P_MFGSTAGE("mfgStage"),
  P_MFGSTAGE_EXACT("mfgStage", GenericSearchType.EXACT_MATCH),
  P_MAG("mag"),
  P_LCM("lcm"),
  P_LCM_EXACT("lcm", GenericSearchType.EXACT_MATCH),
  P_PEP("pep"),
  P_YIELDGROUPNAME("yieldGroupName"),
  P_PGDW("pgdw"),
  P_COMM_YIELD("committedYield", GenericSearchType.FROM_TO),
  P_EXCLUDE_DATE_EXISTS("excludeDate", GenericSearchType.EXISTS),
  P_YIELD_SOURCE("yieldSource"),
  P_PEP_DESCRIPTION("pepDescription"),
  P_BURN_IN_MARKER("burnInMarker"),
  P_POV("pov"),

  // @see NC12SitePartWithYield (in addition to fields from NC12SitePart)
  PY_YIELD_PHASE("yieldPhase"),

  // @see EquipmentCode
  EC_EQUIPMENTCODE("equipmentCode"),
  EC_EQUIPMENTCODENAME("equipmentCodeName"),
  EC_EQUIPMENTCODEMATURITYSTATE("equipmentCodeMaturityState"),
  EC_EQUIPMENTCODELIFECYCLESTATE("equipmentCodeLifecycleState"),
  EC_EQUIPMENTMODEL("equipmentModel"),
  EC_EQUIPMENTMODELLIFECYCLESTATE("equipmentModelLifecycleState"),
  EC_EQUIPMENTPLATFORM("equipmentPlatform"),
  EC_EQUIPMENTVENDOR("equipmentVendor"),
  EC_EQUIPMENTTYPE("equipmentType"),
  EC_RESOURCEGROUP("resourceGroup.resourceGroup"),
  EC_STATUS("status"),
  EC_LAST_UPDATED("lastUpdated"),
  EC_UPDATED_BY("updater.name"),
  EC_TEMP("temp"),
  EC_MAX_SITES("maxSites"),

  // @see Equipment
  E_GLOBAL_ID("globalID"),
  E_EQUIPMENT_CODE("equipmentCode.equipmentCode"),
  E_RESOURCE_CLASS("resourceClass.resourceClass"),
  E_TOOL_ID("toolId"),
  E_PROCESS_STAGE("processStage"),
  E_PLANNING_GROUP("planningGroup"),
  E_DEDICATION("dedication"),
  E_SERIAL_NR("serialNumber"),
  E_ASSET_NR("assetNumber"),
  E_CODIFIED_MODEL("codifiedModel"),
  E_COMMENT_FIELD("comment"),
  E_EC_RESOURCEGROUP("equipmentCode.resourceGroup.resourceGroup"),
  E_EC_RG_DESCRIPTION("equipmentCode.resourceGroup.description"),
  E_EC_EQUIPMENTYPE("equipmentCode.equipmentType"),
  E_EC_NAME("equipmentCode.equipmentCodeName"),
  E_SITE_ACRONYM("site.acronym"),
  E_CONVERIONS_KIT("conversionKit"),
  E_RG_TMDB_NAME("equipmentCode.resourceGroup.tmdb"),
  E_EC_MATSTATE("equipmentCode.equipmentCodeMaturityState"),
  E_EC_MODEL_LCS("equipmentCode.equipmentModelLifecycleState"),
  E_EC_CODE_LCS("equipmentCode.equipmentCodeLifecycleState"),
  E_MODEL("equipmentCode.equipmentModel"),
  E_PLATFORM("equipmentCode.equipmentPlatform"),
  E_VENDOR("equipmentCode.equipmentVendor"),
  E_RG_COMM_CLUSTERNAME("equipmentCode.resourceGroup.communicationClusterName"),
  E_STATUS("status"),
  E_LAST_UPDATED("lastUpdated"),
  E_UPDATED_BY("updater.name"),
  E_SKELETON("skeleton", GenericSearchType.BOOLEAN),
  E_EXTENDED_SITE("extendedSiteAcronym"),
  E_IN_TRANSIT("inTransit", GenericSearchType.BOOLEAN),
  E_EQUIPMENT_CODE_TSMM("equipmentCode.equipmentCode"), // split delimiter between properties is ;
  E_EC_NAME_TSMM("equipmentCode.equipmentCodeName"), // split delimiter between properties is ;

  // @see EquipmentView --> incoming equipment including the event site and
  // transfer in site
  EV_EVENT_SITE("eventSite.acronym"),
  EV_TRANSFERIN_SITE("transferInSite.acronym"),

  // planning view
  PV_LOCATION("location", GenericSearchType.BY_ACRONYM),
  PV_RG("resourceGroup.resourceGroup"),
  PV_RC("resourceClass.resourceClass"),
  PV_RG_NAME("resourceGroup.description"),
  PV_STATUS("status"),

  // resource group
  RG_RG("resourceGroup"),
  RG_DESCRIPTION("description"),
  RG_STATUS("status"),
  RG_LAST_UPDATE("lastUpdated"),
  RG_UPDATE_BY("updater.name"),
  RG_TMDB("tmdb"),
  RG_COMM_CLUSTERNAME("communicationClusterName"),

  // User
  U_WBI("wbi"),
  U_NAME("name"),
  U_PRIMARY_SITE("primaryLocation.acronym"),

  // events
  EVENT_ID("id"),
  EVENT_RG("resourceGroup.resourceGroup"),
  EVENT_RC("resourceClass.resourceClass"),
  EVENT_DESCR(""),
  EVENT_TYPE(""),
  EVENT_STATUS("status"),
  EVENT_ACTION("action"),
  EVENT_START_DATE(""),
  EVENT_END_DATE(""),
  EVENT_REQUESTER("requester.wbi"),
  EVENT_AMOUNT(""),

  EC_P_AVAILABILITY_EQUIPMENTCODE("equipmentCode"),
  EC_P_AVAILABILITY_EQUIPMENTTYPE("equipmentCodeObject.equipmentType"),
  EC_P_AVAILABILITY_EFFECTIVEDATE("effectiveDate"),
  EC_P_AVAILABILITY_SITE("sapCode"),
  EC_P_AVAILABILITY_TESTTYPE("testType"),
  EC_P_AVAILABILITY_VALUE("value", GenericSearchType.FROM_TO),
  EC_P_AVAILABILITY_LASTUPDATED("lastUpdated"),
  EC_P_AVAILABILITY_UPDATEDBY("updater.name"),

  EC_P_INDEXTIME_EQUIPMENTCODE("equipmentCode"),
  EC_P_INDEXTIME_EFFECTIVEDATE("effectiveDate"),
  EC_P_INDEXTIME_SITE("sapCode"),
  EC_P_INDEXTIME_MULTISITE("multiSite"),
  EC_P_INDEXTIME_VALUE("value", GenericSearchType.FROM_TO),
  EC_P_INDEXTIME_LASTUPDATED("lastUpdated"),
  EC_P_INDEXTIME_UPDATEDBY("updater.name"),

  EC_P_LOADTIME_EQUIPMENTCODE("equipmentCode"),
  EC_P_LOADTIME_EFFECTIVEDATE("effectiveDate"),
  EC_P_LOADTIME_SITE("sapCode"),
  EC_P_LOADTIME_VALUE("value", GenericSearchType.FROM_TO),
  EC_P_LOADTIME_LASTUPDATED("lastUpdated"),
  EC_P_LOADTIME_UPDATEDBY("updater.name"),

  EC_P_MANMACHINERATIO_EQUIPMENTCODE("equipmentCode"),
  EC_P_MANMACHINERATIO_EFFECTIVEDATE("effectiveDate"),
  EC_P_MANMACHINERATIO_SITE("sapCode"),
  EC_P_MANMACHINERATIO_VALUE("value", GenericSearchType.FROM_TO),
  EC_P_MANMACHINERATIO_LASTUPDATED("lastUpdated"),
  EC_P_MANMACHINERATIO_UPDATEDBY("updater.name"),

  EC_P_BURN_IN_CHAMBER_EQUIPMENTCODE("equipmentCode"),
  EC_P_BURN_IN_CHAMBER_LOCATION("location.acronym"),
  EC_P_BURN_IN_CHAMBER_SLOTS("slotsPerChamber", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_CHAMBER_SLOTS_COMMENT("commentField"),
  EC_P_BURN_IN_CHAMBER_SLOTS_LASTUPDATED("lastUpdated", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_CHAMBER_SLOTS_UPDATEDBY("updater.name"),

  EC_P_BURN_IN_BOARD_EQUIPMENTCODE("equipmentCode"),
  EC_P_BURN_IN_BOARD_EFFECTIVEDATE("effectiveDate"),
  EC_P_BURN_IN_BOARD_LOCATION("location.acronym"),
  EC_P_BURN_IN_BOARD_PLANNING_NAME("burnInPlanningName"),
  EC_P_BURN_IN_BOARD_TIME_BETWEEN_TURNS("timeBetweenTurns", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_RE_BURN_IN_RATE("reBurnInRate", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_SOCKET_DENSITY("socketDensity", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_SOCKET_UTILIZATION("socketUtilization", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_LAST_UPDATED("lastUpdated"),
  EC_P_BURN_IN_BOARD_UPDATED_BY("updater.name"),
  EC_P_BURN_IN_BOARD_UPDATE_INFO("updateInformation"),

  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_EQUIPMENTCODE("equipmentCode"),
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LOCATION("location.acronym"),
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_FACTOR(
      "chamberAdjustmentFactor", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_COMMENT("commentField"),
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LASTUPDATED("lastUpdated", GenericSearchType.FROM_TO),
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_UPDATEDBY("updater.name"),

  EC_P_OPERATION_UTILIZATION_EQUIPMENTCODE("equipmentCode"),
  EC_P_OPERATION_UTILIZATION_EQUIPMENTCODENAME("equipmentCodeObject.equipmentCodeName"),
  EC_P_OPERATION_UTILIZATION_SITE("sapCode"),
  EC_P_OPERATION_UTILIZATION_VALUE("value", GenericSearchType.FROM_TO),
  EC_P_OPERATION_UTILIZATION_EFFECTIVEDATE("effectiveDate"),
  EC_P_OPERATION_UTILIZATION_LASTUPDATED("lastUpdated"),
  EC_P_OPERATION_UTILIZATION_UPDATEDBY("updater.name"),

  EC_P_RESOURCE_SECONDARY_EQUIPMENTCODE("equipmentCode"),
  EC_P_RESOURCE_SECONDARY_SITE("sapCode"),
  EC_P_RESOURCE_SECONDARY_TESTTYPE("testType"),
  EC_P_RESOURCE_SECONDARY_VALUE("value"),
  EC_P_RESOURCE_SECONDARY_LASTUPDATED("lastUpdated"),
  EC_P_RESOURCE_SECONDARY_UPDATEDBY("updater.name"),

  UR_ISSUE_TWELVENC("part12Nc"),
  UR_ISSUE_SAPCODE("sapLocation"),
  UR_ISSUE_STAGE_ID("stageId"),
  UR_ISSUE_TYPE("issueType"),
  UR_ISSUE_STATUS("status"),
  UR_ISSUE_LASTUPDATED("lastUpdated"),
  UR_ISSUE_UPDATEDBY("updater.name"),

  UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NUMBER("testFlowId"),
  UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NAME("testFlowName"),
  UR_ACTIVATION_FLOW_OVERVIEW_SAPLOCATION("sapLocation"),
  UR_ACTIVATION_FLOW_OVERVIEW_PART_12NC("part12Nc"),
  UR_ACTIVATION_FLOW_OVERVIEW_ACTIVATION_DATE("activationDate"),
  UR_ACTIVATION_FLOW_OVERVIEW_PRIORITY("planningFlowPriority", GenericSearchType.BY_PRIORITY),
  UR_ACTIVATION_FLOW_OVERVIEW_FLOW_TYPE("flowType"),

  TDP_ARAS_ID("arasId"),
  TDP_MANUFACTURER_CODE("manufacturerCode"),
  TDP_SAP_LOCATION("sapLocation"),
  TDP_STEP_TYPE("stepType"),
  TDP_RC("resourceClass.resourceClass"),
  TDP_RG("resourceGroup"),
  TDP_DESCRIPTION("description"),
  TDP_PLANNING_FLAG("planningFlag", GenericSearchType.BOOLEAN),
  TDP_INSERT_DATE("insertDate"),
  TDP_LAST_UPDATED("lastUpdated"),
  TDP_UPDATED_BY("updater.name"),
  TDP_LOCATION_ACRONYM("acronym"),

  BURN_IN_BOARD_ARAS_ID("arasId"),
  BURN_IN_BOARD_ACRONYM("acronym"),
  BURN_IN_BOARD_PLANT_CODE("sapCode"),
  BURN_IN_BOARD_MANUFACTURER_CODE("manufacturerCode"),
  BURN_IN_BOARD_RESOURCE_GROUP("resourceGroup"),
  BURN_IN_BOARD_RC("resourceClass.resourceClass"),
  BURN_IN_BOARD_LCM("lcm"),
  BURN_IN_BOARD_NUMBER_OF_SOCKETS("numberOfSockets", GenericSearchType.FROM_TO),
  BURN_IN_BOARD_PLANNING_NAME("planningName"),
  BURN_IN_BOARD_DESCRIPTION("description"),
  BURN_IN_BOARD_PLANNING_FLAG("planningFlag", GenericSearchType.BOOLEAN),
  BURN_IN_BOARD_INSERT_DATE("insertDate"),
  BURN_IN_BOARD_LAST_UPDATED("lastUpdated"),
  BURN_IN_BOARD_UPDATED_BY("updater.name"),

  PK_POV_EFFICIENCY_LOCATION("location.acronym"),
  PK_POV_EFFICIENCY_POV("pov"),
  PK_POV_EFFICIENCY_PRODUCED("produced", GenericSearchType.FROM_TO),
  PK_POV_EFFICIENCY_EFFICIENCY("efficiency", GenericSearchType.FROM_TO),
  PK_POV_EFFICIENCY_LAST_UPDATED("lastUpdated"),
  PK_POV_EFFICIENCY_UPDATED_BY("updater.name"),

  PK_POV_PARAMS_LOCATION("location.acronym"),
  PK_POV_PARAMS_POV("pov"),
  PK_POV_PARAMS_PACK_TYPE("packType"),
  PK_POV_PARAMS_STEP_TYPE("stepType.stepType"),
  PK_POV_PARAMS_STEP_SEQUENCE("stepSequence"),
  PK_POV_PARAMS_EQUIPMENT_CODE("equipmentCode"),
  PK_POV_PARAMS_LLC_RG("llcRg.resourceGroup"),
  PK_POV_PARAMS_PQ("pq"),
  PK_POV_PARAMS_PKUT("pkut", GenericSearchType.FROM_TO),
  PK_POV_PARAMS_PCA_RESOURCE("pcaResource"),
  PK_POV_PARAMS_PRIORITY("priority"),
  PK_POV_PARAMS_LAST_UPDATED("lastUpdated"),
  PK_POV_PARAMS_UPDATED_BY("updater.name"),

  PK_MANUAL_FLOW_LOCATION("location.acronym"),
  PK_MANUAL_FLOW_PART_12NC("part12Nc"),
  PK_MANUAL_FLOW_STEP_TYPE("stepType.stepType"),
  PK_MANUAL_FLOW_LAST_UPDATED("lastUpdated"),
  PK_MANUAL_FLOW_UPDATED_BY("updater.name"),

  PV_LLC_RG_SITE("site.acronym"),
  PV_LLC_RG("llcRg"),
  PV_LLC_RG_STATUS("status"),

  STEP_MAPPING_SITE("site.acronym"),
  STEP_MAPPING_MFG_STEP("mfgStep"),
  STEP_MAPPING_STEP_TYPE("stepType.stepType"),
  STEP_MAPPING_LAST_UPDATED("lastUpdated"),
  STEP_MAPPING_UPDATED_BY("updater.name"),

  MISSING_LINK_PART12NC("part12NC"),
  MISSING_LINK_LOCATION("location.acronym"),
  MISSING_LINK_PLM12NC("plm12NC"),
  MISSING_LINK_PLM_LCM("plmLcm"),
  MISSING_LINK_PLM_POV("plmPov"),
  MISSING_LINK_PLM_PACK_TYPE("plmPackType"),
  MISSING_LINK_PLM_PQ("plmPq"),
  MISSING_LINK_PACK_FLOW("packFlow"),
  MISSING_LINK_FLOW_SOURCE("flowSource"),
  MISSING_LINK_POV_PARAMS("povParams"),
  MISSING_LINK_ACTIVATED_PLAN_FLOW("activatedPlanFlow"),
  MISSING_LINK_STATUS("status"),
  MISSING_LINK_STATUS_EXACT("status", GenericSearchType.EXACT_MATCH),
  MISSING_LINK_LAST_UPDATED("lastUpdated"),

  // Sites
  LOC_ACRONYM("acronym"),
  LOC_SUBCON("isSubContractor", GenericSearchType.BOOLEAN),
  LOC_TMDBCODE("tmdbCode"),
  LOC_CITY("city"),
  LOC_COUNTRY("country"),
  LOC_SAPCODE("sapCode"),
  LOC_VENDOR_CODE("vendorCode"),
  LOC_PLANNINGENGINE("planningEngine"),
  LOC_STATUS("status"),
  LOC_EXTENDEDSUFFIX("extendedSuffix"),
  LOC_MENUGROUPING("menuGrouping"),
  LOC_LASTUPDATED("lastUpdated"),
  LOC_UPDATEDBY("updater.name"),

  // Manufacturer Codes
  MC_MANUFACTURER_CODE("manufacturerCode"),
  MC_SITE("location.acronym"),
  MC_LASTUPDATED("lastUpdated"),
  MC_UPDATEDBY("updater.name"),

  // UsageRate Test Flow Details Overview
  UR_TESTFLOW_SAPCODE("sapLocation"),
  UR_TESTFLOW_MANUFACTURER_CODE("manufacturingLocation"),
  UR_TESTFLOW_PART_12NC("part12NC"),
  UR_TESTFLOW_PART_TYPE("partType"),
  UR_TESTFLOW_PART_MATURITY("partMaturity"),
  UR_TESTFLOW_MANUFACTURING_STAGE("manufacturingStage"),
  UR_TESTFLOW_CROSS_MANUFACTURING_INDICATOR("crossManufacturingIndicator"),
  UR_TESTFLOW_COMMUNICATION_CLUSTER_NAME("commClusterName"),
  UR_TESTFLOW_MAG("mag"),
  UR_TESTFLOW_PGDW("pgdw"),
  UR_TESTFLOW_ARAS_DEVICE_NAME("arasDeviceName"),
  UR_TESTFLOW_ARAS_FLOW_ID("arasFlowId"),
  UR_TESTFLOW_ARAS_FLOW_NAME("arasFlowName"),
  UR_TESTFLOW_ARAS_TEST_STAGE_ID("arasTestStageId"),
  UR_TESTFLOW_ARAS_TEST_STAGE_NAME("arasTestStageName"),
  UR_TESTFLOW_ARAS_TEST_STAGE_MATURITY("arasTestStageMaturity"),
  UR_TESTFLOW_PLANNING("planning"),
  UR_TESTFLOW_IEMDM_PLANNING_FLOW_NAME("iemdmPlanningFlowName"),
  UR_TESTFLOW_IEMDM_PLANNING_FLOW_ACTIVATION("iemdmPlanningFlowActivation"),
  UR_TESTFLOW_PRIORITY("flowPriority", GenericSearchType.FROM_TO),
  UR_TESTFLOW_STEP_SEQUENCE("stepSequence", GenericSearchType.FROM_TO),
  UR_TESTFLOW_STEP_TYPE("stepType"),
  UR_TESTFLOW_TEMP_CLASS("tempClass"),
  UR_TESTFLOW_TEMPRATURE("temperature", GenericSearchType.FROM_TO),
  UR_TESTFLOW_L1EC("l1EC"),
  UR_TESTFLOW_L1ECNAME("l1ECName"),
  UR_TESTFLOW_L1RG("l1RG"),
  UR_TESTFLOW_L1RGNAME("l1RGName"),
  UR_TESTFLOW_L2EC("l2EC"),
  UR_TESTFLOW_L2ECNAME("l2ECName"),
  UR_TESTFLOW_L2RG("l2RG"),
  UR_TESTFLOW_L2RGNAME("l2RGName"),
  UR_TESTFLOW_TDP_EC("tdpEC"),
  UR_TESTFLOW_TDP_DESCRIPTION("tdpDescription"),
  UR_TESTFLOW_TDP_NUMBER("tdpNumber"),
  UR_TESTFLOW_L4_EC("l4TdpEC"),
  UR_TESTFLOW_L4_DESCRIPTION("l4Description"),
  UR_TESTFLOW_TEST_PROGRAM_NAME("testProgramName"),
  UR_TESTFLOW_MULTISITE("multiSite", GenericSearchType.FROM_TO),
  UR_TESTFLOW_INITIAL_TEST_TIME("initialTestTime", GenericSearchType.FROM_TO),
  UR_TESTFLOW_TEST_TIME("testTime", GenericSearchType.FROM_TO),
  UR_TESTFLOW_AVAILABILITY("availability", GenericSearchType.FROM_TO),
  UR_TESTFLOW_LOADTIME("loadTime", GenericSearchType.FROM_TO),
  UR_TESTFLOW_INDEXTIME("indexTime", GenericSearchType.FROM_TO),
  UR_TESTFLOW_PRODUCT_PERFORMANCE("productPerformance", GenericSearchType.FROM_TO),
  UR_TESTFLOW_USAGERATE("usageRate", GenericSearchType.FROM_TO),
  UR_TESTFLOW_USAGERATE_FINANCIAL("usageRateFinancial", GenericSearchType.FROM_TO),
  UR_TESTFLOW_EFFECTIVE_DATE_USAGERATE("effectiveDateUsageRate"),
  UR_TESTFLOW_STEP_INDICATOR_CATEGORY("stepIndicatorCategory"),
  UR_TESTFLOW_FINANCIAL_PLANNING_FLAG("financialPlanningFlag", GenericSearchType.BOOLEAN),
  UR_TESTFLOW_LASTUPDATED("lastUpdated"),
  UR_TESTFLOW_INFO_TYPE("infoType"),
  UR_TESTFLOW_PART_DESCRIPTION("partDescription"),
  UR_TESTFLOW_ARAS_FLOW_LCM("arasFlowLcm"),
  UR_TESTFLOW_ARAS_STEP_ID("arasStepId"),
  UR_TESTFLOW_ARAS_STEP_NAME("arasStepName"),
  UR_TESTFLOW_ARAS_STEP_MATURITY("arasStepMaturity"),
  UR_TESTFLOW_YIELD("yield"),
  UR_TESTFLOW_STEP_YIELD("stepYield"),
  UR_TESTFLOW_CUM_INPUT_YIELD("cumulativeInputYield"),
  UR_TESTFLOW_CUM_OUTPUT_YIELD("cumulativeOutputYield"),
  UR_TESTFLOW_ADJUSTED_USAGERATE("adjustedUsageRate"),
  UR_TESTFLOW_EFFECTIVE_DATE_INDICATOR("effectiveDateIndicator"),

  UR_PACKINGFLOW_INFO_TYPE("infoType"),
  UR_PACKINGFLOW_SAP_CODE("sapLocation"),
  UR_PACKINGFLOW_PART_12NC("part12NC"),
  UR_PACKINGFLOW_PART_DESCRIPTION("partDescription"),
  UR_PACKINGFLOW_PART_TYPE("partType"),
  UR_PACKINGFLOW_PART_MATURITY("partMaturity"),
  UR_PACKINGFLOW_MAG("mag"),
  UR_PACKINGFLOW_PACKAGE_TYPE_DESCRIPTION("packageTypeDescription"),
  UR_PACKINGFLOW_ASSEMBLY_CG("assemblyCG"),
  UR_PACKINGFLOW_PKG_OUTLINE_VERSION_DESC("pkgOutlineVerDescription"),
  UR_PACKINGFLOW_PKG_OUTLINE_VERSION_LEGACY_PART("pkgOutlineVerLegacyPart"),
  UR_PACKINGFLOW_DRY_PACK("dryPack"),
  UR_PACKINGFLOW_PACKING_TYPE("packingType"),
  UR_PACKINGFLOW_PACKING_BODY_WIDTH("packingBodyWidth"),
  UR_PACKINGFLOW_PACKING_BODY_LENGTH("packingBodyLength"),
  UR_PACKINGFLOW_PACKING_BODY_HEIGHT("packingBodyHeight"),
  UR_PACKINGFLOW_PACKING_METHOD("packingMethod"),
  UR_PACKINGFLOW_PACKING_METHOD_DESCRIPTION("packingMethodDescription"),
  UR_PACKINGFLOW_PACKING_QUANTITY("packingQuantity", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_MFG_STAGE("manufacturingStage"),
  UR_PACKINGFLOW_PACKING_FLOW_ID("packingFlowId"),
  UR_PACKINGFLOW_PACKING_FLOW_NAME("packingFlowName"),
  UR_PACKINGFLOW_PACKING_FLOW_MATURITY("packingFlowMaturity"),
  UR_PACKINGFLOW_PLANNING("planning"),
  UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_NAME("iemdmPlanningFlowName"),
  UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_ACTIVATION("iemdmPlanningFlowActivation"),
  UR_PACKINGFLOW_FLOW_PRIORITY("flowPriority"),
  UR_PACKINGFLOW_STEP_SEQUENCE("stepSequence"),
  UR_PACKINGFLOW_STEP_TYPE("stepType"),
  UR_PACKINGFLOW_STEP_INDICATOR_CATEGORY("stepIndicatorCategory"),
  UR_PACKINGFLOW_PACKAGE_TYPE_FAMILY_NAME("packageTypeFamilyName"),
  UR_PACKINGFLOW_EQUIPMENT_TYPE("equipmentType"),
  UR_PACKINGFLOW_L1_EC("l1EC"),
  UR_PACKINGFLOW_L1_EC_NAME("l1ECName"),
  UR_PACKINGFLOW_L1_RG("l1RG"),
  UR_PACKINGFLOW_L1_RG_NAME("l1RGName"),
  UR_PACKINGFLOW_LLC_RG("llcRG"),
  UR_PACKINGFLOW_EFFECTIVE_DATE_USAGE_RATE("effectiveDateUsageRate"),
  UR_PACKINGFLOW_OPERATION_UTILIZATION("operationUtilization", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_POV_EFFICIENCY("povEfficiency", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_YIELD("yield"),
  UR_PACKINGFLOW_PK_UNIT_TIME("packingUnitTime", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_IDEAL_UNIT_PER_HOUR("idealUnitPerHour"),
  UR_PACKINGFLOW_USAGE_RATE("usageRate", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_UNIT_PER_DAY("unitPerDay"),
  UR_PACKINGFLOW_NET_UNIT_PER_HOUR("netUnitPerHour"),
  UR_PACKINGFLOW_USAGE_RATE_FINANCIAL("usageRateFinancial", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_FINANCIAL_PLANNING_FLAG("financialPlanningFlag"),
  UR_PACKINGFLOW_LAST_UPDATED("lastUpdated"),
  UR_PACKINGFLOW_PRODUCED("produced", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_MAN_MACHINE_RATIO("manMachineRatio", GenericSearchType.FROM_TO),
  UR_PACKINGFLOW_PCA_RESOURCE("pcaResource"),
  UR_PACKINGFLOW_PACKING_STEP_ID("packingStepId"),
  UR_PACKINGFLOW_PACKING_STEP_NAME("packingStepName"),
  UR_PACKINGFLOW_PACKING_STEP_MATURITY("packingStepMaturity"),
  UR_PACKINGFLOW_PACKING_STAGE_ID("packingStageId"),
  UR_PACKINGFLOW_PACKING_STAGE_NAME("packingStageName"),
  UR_PACKINGFLOW_PACKING_STAGE_MATURITY("packingStageMaturity"),
  UR_PACKINGFLOW_MFG_WORKFLOW("mfgWorkflow");

  // -------

  private final String fieldName;
  private final GenericSearchType type;

  GenericSearchSortField(String fieldName) {
    this.fieldName = fieldName;
    this.type = GenericSearchType.DEFAULT;
  }

  GenericSearchSortField(String fieldName, GenericSearchType type) {
    this.fieldName = fieldName;
    this.type = type;
  }

  public String getFieldName() {
    return this.fieldName;
  }

  public GenericSearchType getType() {
    return this.type;
  }
}
