export class ConfigurationItem {
  public configurationKey = "";
  public configurationValue = "";
  public lastUpdated = "";
  public updatedBy = "";
}

export enum ConfigurationValueType {
  DATABASE = "DATABASE",
  I2_VERSION = "I2-version",
  MAX_NOTIFICATIONS = "MaxNotifications",
  DEBOUNCE_TIME = "DebounceTime",
  DEFAULT_EC_AVAILABILITY = "DEFAULT_EC_AVAILABILITY",
  DEFAULT_EC_INDEXTIME_WT = "DEFAULT_EC_INDEXTIME_WT",
  DEFAULT_EC_INDEXTIME_FT = "DEFAULT_EC_INDEXTIME_FT",
  DEFAULT_EC_LOADTIME_WT = "DEFAULT_EC_LOADTIME_WT",
  DEFAULT_EC_LOADTIME_FT = "DEFAULT_EC_LOADTIME_FT",
  DEFAULT_PRODUCTPERFORMANCE_WT = "DEFAULT_PRODUCTPERFORMANCE_WT",
  DEFAULT_PRODUCTPERFORMANCE_FT = "DEFAULT_PRODUCTPERFORMANCE_FT",
  UR_MAX_PRIO_DCM = "UR_MAX_PRIO_DCM",
  UR_MAX_PRIO_JDA = "UR_MAX_PRIO_JDA",
  READ_ONLY_MODE = "READ_ONLY_MODE",
  DEFAULT_EC_PKUT_PK = "DEFAULT_EC_PKUT_PK",
  DEFAULT_EC_POV_EFFICIENCY_PK = "DEFAULT_EC_POV_EFFICIENCY_PK",
  DEFAULT_EC_OPERATION_UTILIZATION_PK = "DEFAULT_EC_OPERATION_UTILIZATION_PK",
  DEFAULT_EC_MAN_MACHINE_RATIO_PK = "DEFAULT_EC_MAN_MACHINE_RATIO_PK",
  APP_VERSION = "AppVersion",
}
