/*
This file contains several classes which can be used to filter & sort any Entity in a generic way.
The idea is that the Angular code only deals with enum's and that the Java then knows how to filter/sort the Entity which may be deeply nested.
In the Java backend the enum (GenericSearchSortField.java) the complete is set to find the corresponding property. For example:
E_EC_RESOURCEGROUP("equipmentCode.resourceGroup.resourceGroup"),

All backend rest call have the same signature, for example:
public genericSearchXxxx(searchValues: GenericSearchArguments, page: number, size: number): Observable<PaginatedContent<XxxPart>>

The GenericSearchArguments class has two list's
- searchArgs: Array<GenericSearchArg> = [];
- sortArgs: Array<GenericSortArg> = [];

Both GenericSearchArg and GenericSortArg have the enum GenericSearchSortField (the enum that was mentioned earlier).
A GenericSearchArg also has the property: value:string, which contains the value to filter on.
The GenericSortArg has the boolean property: descending , indication the sort direction.

Depending on the type of the Entity field, the (string) search value is either:
- For string and enum values: a single value, that will end up as sql: where dbsvalue.toLowerCase() like ('%' + value.toLowerCase() + '%')'
- For numeric and date values: a colon seperated string where the first part is the from-value and the second-part is the to-value.

In addition, the enum mentioned above has a second optional constructor argument to indicate a special search option.
For example, the yield value in parts_list is a string  (because it is a generic value), but we would to search as if it is a number. This can be achieved by :
P_COMM_YIELD("committedYield", GenericSearchType.FROM_TO),
So here we indicate that we use a from/to predicate instead of sql like predicate.
In Angular we set this indication in the getSearchType() method in GenericSearchUtils.

*/

import { SortDirection } from "@angular/material/sort";
import { DateUtils } from "app/utils/date-utils";
import { Location } from "./location";
import { Person } from "./person";
import { Store } from "@ngrx/store";
import * as SystemSelectors from "app/state/system/system.selectors";
import { Injectable } from "@angular/core";

export class GenericSearchArg {
  public value: any;
  public field: GenericSearchSortField;

  public constructor(field: GenericSearchSortField, value: any) {
    this.setValue(value);
    this.field = field;
  }

  public setValue(input: any): void {
    if (Array.isArray(input)) {
      this.value = input.join(";");
    } else {
      this.value = input;
    }
  }
}

export class GenericSortArg {
  public descending: boolean;
  public field: GenericSearchSortField;

  public constructor(field: GenericSearchSortField, descending: boolean) {
    this.descending = descending;
    this.field = field;
  }
}

export interface GenericSearchMultiselectColumn {
  sortField: GenericSearchSortField;
  selectableEnums?: [string, string][];
  initialValue?: string | string[];
  booleanValues?: (boolean | undefined)[];
  columnId?: string;
  sticky?: boolean;
  stickyEnd?: boolean;
  doNotDisplay?: boolean;
  disabled?: boolean;
}

export class GenericSearchArguments {
  public searchArgs: Array<GenericSearchArg> = [];
  public sortArgs: Array<GenericSortArg> = [];

  public getSearchField(
    fld: GenericSearchSortField
  ): GenericSearchArg | undefined {
    return this.searchArgs.find((e) => e.field === fld);
  }

  public setSearchSite(fld: GenericSearchSortField, location: Location): void {
    const searchSiteField = this.getSearchField(fld);
    if (searchSiteField) {
      if (location.id == 0) {
        searchSiteField.value = "";
      } else {
        searchSiteField.value = location.acronym;
      }
    } else {
      console.warn("Search field for site acronym is not set!");
    }
  }
}

export enum GenericSearchSortField {
  // Nc12SitePart
  P_PART12NC = "P_PART12NC",
  P_ACRONYM = "P_ACRONYM",
  P_SITE = "P_SITE",
  P_DESCRIPTION = "P_DESCRIPTION",
  P_TYPE = "P_TYPE",
  P_TYPEGROUP = "P_TYPEGROUP",
  P_MFGSTAGE = "P_MFGSTAGE",
  P_MFGSTAGE_EXACT = "P_MFGSTAGE_EXACT",
  P_MAG = "P_MAG",
  P_LCM = "P_LCM",
  P_LCM_EXACT = "P_LCM_EXACT",
  P_PEP = "P_PEP",
  P_YIELDGROUPNAME = "P_YIELDGROUPNAME",
  P_BURN_IN_MARKER = "P_BURN_IN_MARKER",
  P_POV = "P_POV",
  P_PGDW = "P_PGDW",
  P_COMM_YIELD = "P_COMM_YIELD",
  P_EXCLUDE_DATE_EXISTS = "P_EXCLUDE_DATE_EXISTS",
  P_PEP_DESCRIPTION = "P_PEP_DESCRIPTION",
  P_YIELD_SOURCE = "P_YIELD_SOURCE",

  // Nc12SitePart with Yield
  PY_YIELD_PHASE = "PY_YIELD_PHASE",

  // EquipmentCode
  EC_EQUIPMENTCODE = "EC_EQUIPMENTCODE",
  EC_EQUIPMENTCODENAME = "EC_EQUIPMENTCODENAME",
  EC_EQUIPMENTCODEMATURITYSTATE = "EC_EQUIPMENTCODEMATURITYSTATE",
  EC_EQUIPMENTCODELIFECYCLESTATE = "EC_EQUIPMENTCODELIFECYCLESTATE",
  EC_EQUIPMENTMODEL = "EC_EQUIPMENTMODEL",
  EC_EQUIPMENTMODELLIFECYCLESTATE = "EC_EQUIPMENTMODELLIFECYCLESTATE",
  EC_EQUIPMENTPLATFORM = "EC_EQUIPMENTPLATFORM",
  EC_EQUIPMENTVENDOR = "EC_EQUIPMENTVENDOR",
  EC_EQUIPMENTTYPE = "EC_EQUIPMENTTYPE",
  EC_RESOURCEGROUP = "EC_RESOURCEGROUP",
  EC_STATUS = "EC_STATUS",
  EC_LAST_UPDATED = "EC_LAST_UPDATED",
  EC_UPDATED_BY = "EC_UPDATED_BY",

  // Equipment
  E_GLOBAL_ID = "E_GLOBAL_ID",
  E_EQUIPMENT_CODE = "E_EQUIPMENT_CODE",
  E_RESOURCE_CLASS = "E_RESOURCE_CLASS",
  E_TOOL_ID = "E_TOOL_ID",
  E_PROCESS_STAGE = "E_PROCESS_STAGE",
  E_PLANNING_GROUP = "E_PLANNING_GROUP",
  E_DEDICATION = "E_DEDICATION",
  E_SERIAL_NR = "E_SERIAL_NR",
  E_ASSET_NR = "E_ASSET_NR",
  E_CODIFIED_MODEL = "E_CODIFIED_MODEL",
  E_COMMENT_FIELD = "E_COMMENT_FIELD",
  E_EC_RESOURCEGROUP = "E_EC_RESOURCEGROUP",
  E_EC_RG_DESCRIPTION = "E_EC_RG_DESCRIPTION",
  E_EC_EQUIPMENTYPE = "E_EC_EQUIPMENTYPE",
  E_EC_NAME = "E_EC_NAME",
  E_SITE_ACRONYM = "E_SITE_ACRONYM",
  E_STATUS = "E_STATUS",
  E_LAST_UPDATED = "E_LAST_UPDATED",
  E_UPDATED_BY = "E_UPDATED_BY",
  E_CONVERIONS_KIT = "E_CONVERIONS_KIT",
  E_RG_TMDB_NAME = "E_RG_TMDB_NAME",
  E_EC_MATSTATE = "E_EC_MATSTATE",
  E_EC_MODEL_LCS = "E_EC_MODEL_LCS",
  E_EC_CODE_LCS = "E_EC_CODE_LCS",
  E_MODEL = "E_MODEL",
  E_PLATFORM = "E_PLATFORM",
  E_VENDOR = "E_VENDOR",
  E_RG_COMM_CLUSTERNAME = "E_RG_COMM_CLUSTERNAME",
  E_SKELETON = "E_SKELETON",
  E_EXTENDED_SITE = "E_EXTENDED_SITE",
  E_IN_TRANSIT = "E_IN_TRANSIT",
  E_EQUIPMENT_CODE_TSMM = "E_EQUIPMENT_CODE_TSMM",
  E_EC_NAME_TSMM = "E_EC_NAME_TSMM",

  // todo: add more properties for the event view variant
  EV_EVENT_SITE = "EV_EVENT_SITE",
  EV_TRANSFERIN_SITE = "EV_TRANSFERIN_SITE",

  // Planning view
  PV_LOCATION = "PV_LOCATION",
  PV_RG = "PV_RG",
  PV_RC = "PV_RC",
  PV_RG_NAME = "PV_RG_NAME",
  PV_STATUS = "PV_STATUS",

  // resource group
  RG_RG = "RG_RG",
  RG_DESCRIPTION = "RG_DESCRIPTION",
  RG_STATUS = "RG_STATUS",
  RG_LAST_UPDATE = "RG_LAST_UPDATE",
  RG_UPDATE_BY = "RG_UPDATE_BY",
  RG_TMDB = "RG_TMDB",
  RG_COMM_CLUSTERNAME = "RG_COMM_CLUSTERNAME",

  // user
  U_WBI = "U_WBI",
  U_NAME = "U_NAME",
  U_PRIMARY_SITE = "U_PRIMARY_SITE",

  // approval management
  APPROVAL_MANAGEMENT_EVENT_TYPE = "APPROVAL_MANAGEMENT_EVENT_TYPE",
  APPROVAL_MANAGEMENT_LEVEL = "APPROVAL_MANAGEMENT_LEVEL",
  APPROVAL_MANAGEMENT_ROLE = "APPROVAL_MANAGEMENT_ROLE",
  APPROVAL_MANAGEMENT_UPDATEDBY = "APPROVAL_MANAGEMENT_UPDATEDBY",
  APPROVAL_MANAGEMENT_LASTUPDATED = "APPROVAL_MANAGEMENT_LASTUPDATED",

  // events
  EVENT_ID = "EVENT_ID",
  EVENT_RG = "EVENT_RG",
  EVENT_RC = "EVENT_RC",
  EVENT_DEDICATION = "EVENT_DEDICATION",
  EVENT_DESCR = "EVENT_DESCR",
  EVENT_TYPE = "EVENT_TYPE",
  EVENT_STATUS = "EVENT_STATUS",
  EVENT_ACTION = "EVENT_ACTION",
  EVENT_START_DATE = "EVENT_START_DATE",
  EVENT_END_DATE = "EVENT_END_DATE",
  EVENT_REQUESTER = "EVENT_REQUESTER",
  EVENT_AMOUNT = "EVENT_AMOUNT",
  EVENT_COMPLETED = "EVENT_COMPLETED",

  // resource class
  RC_RESOURCECLASS = "RC_RESOURCECLASS",
  RC_DESCRIPTION = "RC_DESCRIPTION",
  RC_LASTUPDATED = "RC_LASTUPDATED",
  RC_UPDATEDBY = "RC_UPDATEDBY",

  // Sites
  LOC_ACRONYM = "LOC_ACRONYM",
  LOC_SUBCON = "LOC_SUBCON",
  LOC_TMDBCODE = "LOC_TMDBCODE",
  LOC_CITY = "LOC_CITY",
  LOC_COUNTRY = "LOC_COUNTRY",
  LOC_SAPCODE = "LOC_SAPCODE",
  LOC_VENDOR_CODE = "LOC_VENDOR_CODE",
  LOC_PLANNINGENGINE = "LOC_PLANNINGENGINE",
  LOC_STATUS = "LOC_STATUS",
  LOC_EXTENDEDSUFFIX = "LOC_EXTENDEDSUFFIX",
  LOC_MENUGROUPING = "LOC_MENUGROUPING",
  LOC_LASTUPDATED = "LOC_LASTUPDATED",
  LOC_UPDATEDBY = "LOC_UPDATEDBY",

  // Manufacturer Codes
  MC_MANUFACTURER_CODE = "MC_MANUFACTURER_CODE",
  MC_SITE = "MC_SITE",
  MC_LASTUPDATED = "MC_LASTUPDATED",
  MC_UPDATEDBY = "MC_UPDATEDBY",

  EC_P_AVAILABILITY_EQUIPMENTCODE = "EC_P_AVAILABILITY_EQUIPMENTCODE",
  EC_P_AVAILABILITY_EQUIPMENTTYPE = "EC_P_AVAILABILITY_EQUIPMENTTYPE",
  EC_P_AVAILABILITY_EFFECTIVEDATE = "EC_P_AVAILABILITY_EFFECTIVEDATE",
  EC_P_AVAILABILITY_SITE = "EC_P_AVAILABILITY_SITE",
  EC_P_AVAILABILITY_TESTTYPE = "EC_P_AVAILABILITY_TESTTYPE",
  EC_P_AVAILABILITY_VALUE = "EC_P_AVAILABILITY_VALUE",
  EC_P_AVAILABILITY_LASTUPDATED = "EC_P_AVAILABILITY_LASTUPDATED",
  EC_P_AVAILABILITY_UPDATEDBY = "EC_P_AVAILABILITY_UPDATEDBY",

  EC_P_INDEXTIME_EQUIPMENTCODE = "EC_P_INDEXTIME_EQUIPMENTCODE",
  EC_P_INDEXTIME_EFFECTIVEDATE = "EC_P_INDEXTIME_EFFECTIVEDATE",
  EC_P_INDEXTIME_SITE = "EC_P_INDEXTIME_SITE",
  EC_P_INDEXTIME_MULTISITE = "EC_P_INDEXTIME_MULTISITE",
  EC_P_INDEXTIME_VALUE = "EC_P_INDEXTIME_VALUE",
  EC_P_INDEXTIME_LASTUPDATED = "EC_P_INDEXTIME_LASTUPDATED",
  EC_P_INDEXTIME_UPDATEDBY = "EC_P_INDEXTIME_UPDATEDBY",

  EC_P_LOADTIME_EQUIPMENTCODE = "EC_P_LOADTIME_EQUIPMENTCODE",
  EC_P_LOADTIME_EFFECTIVEDATE = "EC_P_LOADTIME_EFFECTIVEDATE",
  EC_P_LOADTIME_SITE = "EC_P_LOADTIME_SITE",
  EC_P_LOADTIME_VALUE = "EC_P_LOADTIME_VALUE",
  EC_P_LOADTIME_LASTUPDATED = "EC_P_LOADTIME_LASTUPDATED",
  EC_P_LOADTIME_UPDATEDBY = "EC_P_LOADTIME_UPDATEDBY",

  EC_P_MANMACHINERATIO_EQUIPMENTCODE = "EC_P_MANMACHINERATIO_EQUIPMENTCODE",
  EC_P_MANMACHINERATIO_EQUIPMENTCODENAME = "EC_P_MANMACHINERATIO_EQUIPMENTCODENAME",
  EC_P_MANMACHINERATIO_EFFECTIVEDATE = "EC_P_MANMACHINERATIO_EFFECTIVEDATE",
  EC_P_MANMACHINERATIO_SITE = "EC_P_MANMACHINERATIO_SITE",
  EC_P_MANMACHINERATIO_VALUE = "EC_P_MANMACHINERATIO_VALUE",
  EC_P_MANMACHINERATIO_LASTUPDATED = "EC_P_MANMACHINERATIO_LASTUPDATED",
  EC_P_MANMACHINERATIO_UPDATEDBY = "EC_P_MANMACHINERATIO_UPDATEDBY",
  EC_P_OPERATION_UTILIZATION_EQUIPMENTCODE = "EC_P_OPERATION_UTILIZATION_EQUIPMENTCODE",
  EC_P_OPERATION_UTILIZATION_EQUIPMENTCODENAME = "EC_P_OPERATION_UTILIZATION_EQUIPMENTCODENAME",
  EC_P_OPERATION_UTILIZATION_EFFECTIVEDATE = "EC_P_OPERATION_UTILIZATION_EFFECTIVEDATE",
  EC_P_OPERATION_UTILIZATION_SITE = "EC_P_OPERATION_UTILIZATION_SITE",
  EC_P_OPERATION_UTILIZATION_VALUE = "EC_P_OPERATION_UTILIZATION_VALUE",
  EC_P_OPERATION_UTILIZATION_LASTUPDATED = "EC_P_OPERATION_UTILIZATION_LASTUPDATED",
  EC_P_OPERATION_UTILIZATION_UPDATEDBY = "EC_P_OPERATION_UTILIZATION_UPDATEDBY",

  EC_P_BURN_IN_CHAMBER_EQUIPMENTCODE = "EC_P_BURN_IN_CHAMBER_EQUIPMENTCODE",
  EC_P_BURN_IN_CHAMBER_LOCATION = "EC_P_BURN_IN_CHAMBER_LOCATION",
  EC_P_BURN_IN_CHAMBER_SLOTS = "EC_P_BURN_IN_CHAMBER_SLOTS",
  EC_P_BURN_IN_CHAMBER_SLOTS_COMMENT = "EC_P_BURN_IN_CHAMBER_SLOTS_COMMENT",
  EC_P_BURN_IN_CHAMBER_SLOTS_LASTUPDATED = "EC_P_BURN_IN_CHAMBER_SLOTS_LASTUPDATED",
  EC_P_BURN_IN_CHAMBER_SLOTS_UPDATEDBY = "EC_P_BURN_IN_CHAMBER_SLOTS_UPDATEDBY",

  EC_P_BURN_IN_BOARD_EQUIPMENTCODE = "EC_P_BURN_IN_BOARD_EQUIPMENTCODE",
  EC_P_BURN_IN_BOARD_EFFECTIVEDATE = "EC_P_BURN_IN_BOARD_EFFECTIVEDATE",
  EC_P_BURN_IN_BOARD_LOCATION = "EC_P_BURN_IN_BOARD_LOCATION",
  EC_P_BURN_IN_BOARD_PLANNING_NAME = "EC_P_BURN_IN_BOARD_PLANNING_NAME",
  EC_P_BURN_IN_BOARD_TIME_BETWEEN_TURNS = "EC_P_BURN_IN_BOARD_TIME_BETWEEN_TURNS",
  EC_P_BURN_IN_BOARD_RE_BURN_IN_RATE = "EC_P_BURN_IN_BOARD_RE_BURN_IN_RATE",
  EC_P_BURN_IN_BOARD_SOCKET_DENSITY = "EC_P_BURN_IN_BOARD_SOCKET_DENSITY",
  EC_P_BURN_IN_BOARD_SOCKET_UTILIZATION = "EC_P_BURN_IN_BOARD_SOCKET_UTILIZATION",
  EC_P_BURN_IN_BOARD_LAST_UPDATED = "EC_P_BURN_IN_BOARD_LAST_UPDATED",
  EC_P_BURN_IN_BOARD_UPDATED_BY = "EC_P_BURN_IN_BOARD_UPDATED_BY",
  EC_P_BURN_IN_BOARD_UPDATE_INFO = "EC_P_BURN_IN_BOARD_UPDATE_INFO",

  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_EQUIPMENTCODE = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_EQUIPMENTCODE",
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LOCATION = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LOCATION",
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_FACTOR = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_FACTOR",
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_COMMENT = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_COMMENT",
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LASTUPDATED = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LASTUPDATED",
  EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_UPDATEDBY = "EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_UPDATEDBY",

  EC_P_RESOURCE_SECONDARY_EQUIPMENTCODE = "EC_P_RESOURCE_SECONDARY_EQUIPMENTCODE",
  EC_P_RESOURCE_SECONDARY_SITE = "EC_P_RESOURCE_SECONDARY_SITE",
  EC_P_RESOURCE_SECONDARY_TESTTYPE = "EC_P_RESOURCE_SECONDARY_TESTTYPE",
  EC_P_RESOURCE_SECONDARY_VALUE = "EC_P_RESOURCE_SECONDARY_VALUE",
  EC_P_RESOURCE_SECONDARY_LASTUPDATED = "EC_P_RESOURCE_SECONDARY_LASTUPDATED",
  EC_P_RESOURCE_SECONDARY_UPDATEDBY = "EC_P_RESOURCE_SECONDARY_UPDATEDBY",

  NOTIFICATION_READ = "NOTIFICATION_READ",
  NOTIFICATION_TITLE = "NOTIFICATION_TITLE",
  NOTIFICATION_SEVERITYLEVEL = "NOTIFICATION_SEVERITYLEVEL",
  NOTIFICATION_TIMESTAMP = "NOTIFICATION_TIMESTAMP",

  REQUEST_REQUESTER = "REQUEST_REQUESTER",
  REQUEST_DESCRIPTION = "REQUEST_DESCRIPTION",
  REQUEST_STATUS = "REQUEST_STATUS",
  REQUEST_SUBMITDATE = "REQUEST_SUBMITDATE",
  REQUEST_ACTIONS = "REQUEST_ACTIONS",

  APPROVAL_ID = "APPROVAL_ID",
  APPROVAL_REQUESTER = "APPROVAL_REQUESTER",
  APPROVAL_DESCRIPTION = "APPROVAL_DESCRIPTION",
  APPROVAL_STATUS = "APPROVAL_STATUS",
  APPROVAL_SUBMITDATE = "APPROVAL_SUBMITDATE",
  APPROVAL_NUMBEREVENTS = "APPROVAL_NUMBEREVENTS",
  APPROVAL_ACTIONS = "APPROVAL_ACTIONS",

  UR_ISSUE_TWELVENC = "UR_ISSUE_TWELVENC",
  UR_ISSUE_SAPCODE = "UR_ISSUE_SAPCODE",
  UR_ISSUE_STAGE_ID = "UR_ISSUE_STAGE_ID",
  UR_ISSUE_TYPE = "UR_ISSUE_TYPE",
  UR_ISSUE_STATUS = "UR_ISSUE_STATUS",
  UR_ISSUE_LASTUPDATED = "UR_ISSUE_LASTUPDATED",
  UR_ISSUE_UPDATEDBY = "UR_ISSUE_UPDATEDBY",

  UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NUMBER = "UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NUMBER",
  UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NAME = "UR_ACTIVATION_FLOW_OVERVIEW_TESTFLOW_NAME",
  UR_ACTIVATION_FLOW_OVERVIEW_SAPLOCATION = "UR_ACTIVATION_FLOW_OVERVIEW_SAPLOCATION",
  UR_ACTIVATION_FLOW_OVERVIEW_PART_12NC = "UR_ACTIVATION_FLOW_OVERVIEW_PART_12NC",
  UR_ACTIVATION_FLOW_OVERVIEW_FLOW_TYPE = "UR_ACTIVATION_FLOW_OVERVIEW_FLOW_TYPE",
  UR_ACTIVATION_FLOW_OVERVIEW_ACTIVATION_DATE = "UR_ACTIVATION_FLOW_OVERVIEW_ACTIVATION_DATE",
  UR_ACTIVATION_FLOW_OVERVIEW_PRIORITY = "UR_ACTIVATION_FLOW_OVERVIEW_PRIORITY",

  TDP_ARAS_ID = "TDP_ARAS_ID",
  TDP_MANUFACTURER_CODE = "TDP_MANUFACTURER_CODE",
  TDP_SAP_LOCATION = "TDP_SAP_LOCATION",
  TDP_STEP_TYPE = "TDP_STEP_TYPE",
  TDP_RC = "TDP_RC",
  TDP_RG = "TDP_RG",
  TDP_DESCRIPTION = "TDP_DESCRIPTION",
  TDP_PLANNING_FLAG = "TDP_PLANNING_FLAG",
  TDP_INSERT_DATE = "TDP_INSERT_DATE",
  TDP_LAST_UPDATED = "TDP_LAST_UPDATED",
  TDP_UPDATED_BY = "TDP_UPDATED_BY",
  TDP_LOCATION_ACRONYM = "TDP_LOCATION_ACRONYM",

  BURN_IN_BOARD_ARAS_ID = "BURN_IN_BOARD_ARAS_ID",
  BURN_IN_BOARD_ACRONYM = "BURN_IN_BOARD_ACRONYM",
  BURN_IN_BOARD_PLANT_CODE = "BURN_IN_BOARD_PLANT_CODE",
  BURN_IN_BOARD_MANUFACTURER_CODE = "BURN_IN_BOARD_MANUFACTURER_CODE",
  BURN_IN_BOARD_RESOURCE_GROUP = "BURN_IN_BOARD_RESOURCE_GROUP",
  BURN_IN_BOARD_RC = "BURN_IN_BOARD_RC",
  BURN_IN_BOARD_LCM = "BURN_IN_BOARD_LCM",
  BURN_IN_BOARD_NUMBER_OF_SOCKETS = "BURN_IN_BOARD_NUMBER_OF_SOCKETS",
  BURN_IN_BOARD_PLANNING_NAME = "BURN_IN_BOARD_PLANNING_NAME",
  BURN_IN_BOARD_DESCRIPTION = "BURN_IN_BOARD_DESCRIPTION",
  BURN_IN_BOARD_PLANNING_FLAG = "BURN_IN_BOARD_PLANNING_FLAG",
  BURN_IN_BOARD_INSERT_DATE = "BURN_IN_BOARD_INSERT_DATE",
  BURN_IN_BOARD_LAST_UPDATED = "BURN_IN_BOARD_LAST_UPDATED",
  BURN_IN_BOARD_UPDATED_BY = "BURN_IN_BOARD_UPDATED_BY",

  PK_POV_PARAMS_LOCATION = "PK_POV_PARAMS_LOCATION",
  PK_POV_PARAMS_POV = "PK_POV_PARAMS_POV",
  PK_POV_PARAMS_PACK_TYPE = "PK_POV_PARAMS_PACK_TYPE",
  PK_POV_PARAMS_STEP_TYPE = "PK_POV_PARAMS_STEP_TYPE",
  PK_POV_PARAMS_STEP_SEQUENCE = "PK_POV_PARAMS_STEP_SEQUENCE",
  PK_POV_PARAMS_EQUIPMENT_CODE = "PK_POV_PARAMS_EQUIPMENT_CODE",
  PK_POV_PARAMS_LLC_RG = "PK_POV_PARAMS_LLC_RG",
  PK_POV_PARAMS_PQ = "PK_POV_PARAMS_PQ",
  PK_POV_PARAMS_PKUT = "PK_POV_PARAMS_PKUT",
  PK_POV_PARAMS_PCA_RESOURCE = "PK_POV_PARAMS_PCA_RESOURCE",
  PK_POV_PARAMS_PRIORITY = "PK_POV_PARAMS_PRIORITY",
  PK_POV_PARAMS_LAST_UPDATED = "PK_POV_PARAMS_LAST_UPDATED",
  PK_POV_PARAMS_UPDATED_BY = "PK_POV_PARAMS_UPDATED_BY",

  /**
   * Packing
   */
  PK_POV_EFFICIENCY_LOCATION = "PK_POV_EFFICIENCY_LOCATION",
  PK_POV_EFFICIENCY_POV = "PK_POV_EFFICIENCY_POV",
  PK_POV_EFFICIENCY_PRODUCED = "PK_POV_EFFICIENCY_PRODUCED",
  PK_POV_EFFICIENCY_EFFICIENCY = "PK_POV_EFFICIENCY_EFFICIENCY",
  PK_POV_EFFICIENCY_LAST_UPDATED = "PK_POV_EFFICIENCY_LAST_UPDATED",
  PK_POV_EFFICIENCY_UPDATED_BY = "PK_POV_EFFICIENCY_UPDATED_BY",

  PK_MANUAL_FLOW_LOCATION = "PK_MANUAL_FLOW_LOCATION",
  PK_MANUAL_FLOW_PART_12NC = "PK_MANUAL_FLOW_PART_12NC",
  PK_MANUAL_FLOW_STEP_TYPE = "PK_MANUAL_FLOW_STEP_TYPE",
  PK_MANUAL_FLOW_LAST_UPDATED = "PK_MANUAL_FLOW_LAST_UPDATED",
  PK_MANUAL_FLOW_UPDATED_BY = "PK_MANUAL_FLOW_UPDATED_BY",

  // LLC_RG capacity
  PV_LLC_RG_SITE = "PV_LLC_RG_SITE",
  PV_LLC_RG = "PV_LLC_RG",
  PV_LLC_RG_STATUS = "PV_LLC_RG_STATUS",

  MISSING_LINK_PART12NC = "MISSING_LINK_PART12NC",
  MISSING_LINK_LOCATION = "MISSING_LINK_LOCATION",
  MISSING_LINK_PLM12NC = "MISSING_LINK_PLM12NC",
  MISSING_LINK_PLM_LCM = "MISSING_LINK_PLM_LCM",
  MISSING_LINK_PLM_POV = "MISSING_LINK_PLM_POV",
  MISSING_LINK_PLM_PACK_TYPE = "MISSING_LINK_PLM_PACK_TYPE",
  MISSING_LINK_PLM_PQ = "MISSING_LINK_PLM_PQ",
  MISSING_LINK_PACK_FLOW = "MISSING_LINK_PACK_FLOW",
  MISSING_LINK_FLOW_SOURCE = "MISSING_LINK_FLOW_SOURCE",
  MISSING_LINK_POV_PARAMS = "MISSING_LINK_POV_PARAMS",
  MISSING_LINK_ACTIVATED_PLAN_FLOW = "MISSING_LINK_ACTIVATED_PLAN_FLOW",
  MISSING_LINK_STATUS = "MISSING_LINK_STATUS",
  MISSING_LINK_STATUS_EXACT = "MISSING_LINK_STATUS_EXACT",
  MISSING_LINK_LAST_UPDATED = "MISSING_LINK_LAST_UPDATED",

  /**
   * UsageRate Test Flow Details Overview
   */
  UR_TESTFLOW_SAPCODE = "UR_TESTFLOW_SAPCODE",
  UR_TESTFLOW_MANUFACTURER_CODE = "UR_TESTFLOW_MANUFACTURER_CODE",
  UR_TESTFLOW_PART_12NC = "UR_TESTFLOW_PART_12NC",
  UR_TESTFLOW_PART_TYPE = "UR_TESTFLOW_PART_TYPE",
  UR_TESTFLOW_PART_MATURITY = "UR_TESTFLOW_PART_MATURITY",
  UR_TESTFLOW_MANUFACTURING_STAGE = "UR_TESTFLOW_MANUFACTURING_STAGE",
  UR_TESTFLOW_CROSS_MANUFACTURING_INDICATOR = "UR_TESTFLOW_CROSS_MANUFACTURING_INDICATOR",
  UR_TESTFLOW_COMMUNICATION_CLUSTER_NAME = "UR_TESTFLOW_COMMUNICATION_CLUSTER_NAME",
  UR_TESTFLOW_MAG = "UR_TESTFLOW_MAG",
  UR_TESTFLOW_PGDW = "UR_TESTFLOW_PGDW",
  UR_TESTFLOW_ARAS_DEVICE_NAME = "UR_TESTFLOW_ARAS_DEVICE_NAME",
  UR_TESTFLOW_ARAS_FLOW_ID = "UR_TESTFLOW_ARAS_FLOW_ID",
  UR_TESTFLOW_ARAS_FLOW_NAME = "UR_TESTFLOW_ARAS_FLOW_NAME",
  UR_TESTFLOW_ARAS_TEST_STAGE_ID = "UR_TESTFLOW_ARAS_TEST_STAGE_ID",
  UR_TESTFLOW_ARAS_TEST_STAGE_NAME = "UR_TESTFLOW_ARAS_TEST_STAGE_NAME",
  UR_TESTFLOW_ARAS_TEST_STAGE_MATURITY = "UR_TESTFLOW_ARAS_TEST_STAGE_MATURITY",
  UR_TESTFLOW_PLANNING = "UR_TESTFLOW_PLANNING",
  UR_TESTFLOW_IEMDM_PLANNING_FLOW_NAME = "UR_TESTFLOW_IEMDM_PLANNING_FLOW_NAME",
  UR_TESTFLOW_IEMDM_PLANNING_FLOW_ACTIVATION = "UR_TESTFLOW_IEMDM_PLANNING_FLOW_ACTIVATION",
  UR_TESTFLOW_PRIORITY = "UR_TESTFLOW_PRIORITY",
  UR_TESTFLOW_STEP_SEQUENCE = "UR_TESTFLOW_STEP_SEQUENCE",
  UR_TESTFLOW_STEP_TYPE = "UR_TESTFLOW_STEP_TYPE",
  UR_TESTFLOW_STEP_INDICATOR_CATEGORY = "UR_TESTFLOW_STEP_INDICATOR_CATEGORY",
  UR_TESTFLOW_TEMP_CLASS = "UR_TESTFLOW_TEMP_CLASS",
  UR_TESTFLOW_TEMPRATURE = "UR_TESTFLOW_TEMPRATURE",
  UR_TESTFLOW_L1EC = "UR_TESTFLOW_L1EC",
  UR_TESTFLOW_L1ECNAME = "UR_TESTFLOW_L1ECNAME",
  UR_TESTFLOW_L1RG = "UR_TESTFLOW_L1RG",
  UR_TESTFLOW_L1RGNAME = "UR_TESTFLOW_L1RGNAME",
  UR_TESTFLOW_L2EC = "UR_TESTFLOW_L2EC",
  UR_TESTFLOW_L2ECNAME = "UR_TESTFLOW_L2ECNAME",
  UR_TESTFLOW_L2RG = "UR_TESTFLOW_L2RG",
  UR_TESTFLOW_L2RGNAME = "UR_TESTFLOW_L2RGNAME",
  UR_TESTFLOW_TDP_EC = "UR_TESTFLOW_TDP_EC",
  UR_TESTFLOW_TDP_DESCRIPTION = "UR_TESTFLOW_TDP_DESCRIPTION",
  UR_TESTFLOW_TDP_NUMBER = "UR_TESTFLOW_TDP_NUMBER",
  UR_TESTFLOW_L4_EC = "UR_TESTFLOW_L4_EC",
  UR_TESTFLOW_L4_DESCRIPTION = "UR_TESTFLOW_L4_DESCRIPTION",
  UR_TESTFLOW_TEST_PROGRAM_NAME = "UR_TESTFLOW_TEST_PROGRAM_NAME",
  UR_TESTFLOW_MULTISITE = "UR_TESTFLOW_MULTISITE",
  UR_TESTFLOW_INITIAL_TEST_TIME = "UR_TESTFLOW_INITIAL_TEST_TIME",
  UR_TESTFLOW_TEST_TIME = "UR_TESTFLOW_TEST_TIME",
  UR_TESTFLOW_AVAILABILITY = "UR_TESTFLOW_AVAILABILITY",
  UR_TESTFLOW_LOADTIME = "UR_TESTFLOW_LOADTIME",
  UR_TESTFLOW_INDEXTIME = "UR_TESTFLOW_INDEXTIME",
  UR_TESTFLOW_PRODUCT_PERFORMANCE = "UR_TESTFLOW_PRODUCT_PERFORMANCE",
  UR_TESTFLOW_USAGERATE = "UR_TESTFLOW_USAGERATE",
  UR_TESTFLOW_USAGERATE_FINANCIAL = "UR_TESTFLOW_USAGERATE_FINANCIAL",
  UR_TESTFLOW_EFFECTIVE_DATE_USAGERATE = "UR_TESTFLOW_EFFECTIVE_DATE_USAGERATE",
  UR_TESTFLOW_FINANCIAL_PLANNING_FLAG = "UR_TESTFLOW_FINANCIAL_PLANNING_FLAG",
  UR_TESTFLOW_LASTUPDATED = "UR_TESTFLOW_LASTUPDATED",
  UR_TESTFLOW_INFO_TYPE = "UR_TESTFLOW_INFO_TYPE",
  UR_TESTFLOW_PART_DESCRIPTION = "UR_TESTFLOW_PART_DESCRIPTION",
  UR_TESTFLOW_ARAS_FLOW_LCM = "UR_TESTFLOW_ARAS_FLOW_LCM",
  UR_TESTFLOW_ARAS_STEP_ID = "UR_TESTFLOW_ARAS_STEP_ID",
  UR_TESTFLOW_ARAS_STEP_NAME = "UR_TESTFLOW_ARAS_STEP_NAME",
  UR_TESTFLOW_ARAS_STEP_MATURITY = "UR_TESTFLOW_ARAS_STEP_MATURITY",
  UR_TESTFLOW_YIELD = "UR_TESTFLOW_YIELD",
  UR_TESTFLOW_STEP_YIELD = "UR_TESTFLOW_STEP_YIELD",
  UR_TESTFLOW_CUM_INPUT_YIELD = "UR_TESTFLOW_CUM_INPUT_YIELD",
  UR_TESTFLOW_CUM_OUTPUT_YIELD = "UR_TESTFLOW_CUM_OUTPUT_YIELD",
  UR_TESTFLOW_ADJUSTED_USAGERATE = "UR_TESTFLOW_ADJUSTED_USAGERATE",
  UR_TESTFLOW_EFFECTIVE_DATE_INDICATOR = "UR_TESTFLOW_EFFECTIVE_DATE_INDICATOR",
  /**
   * Usage Rate PLM Stage information
   */
  UR_PLM_STAGE_FLOW_ID = "UR_PLM_STAGE_FLOW_ID",
  UR_PLM_STAGE_FLOW_NAME = "UR_PLM_STAGE_FLOW_NAME",
  UR_PLM_STAGE_FLOW_LCM = "UR_PLM_STAGE_FLOW_LCM",
  UR_PLM_STAGE_STAGE_ID = "UR_PLM_STAGE_STAGE_ID",
  UR_PLM_STAGE_STEP_TYPE = "UR_PLM_STAGE_STEP_TYPE",
  UR_PLM_STAGE_STEP_ORDER = "UR_PLM_STAGE_STEP_ORDER",
  UR_PLM_STAGE_TEMPERATURE = "UR_PLM_STAGE_TEMPERATURE",
  UR_PLM_STAGE_STAGE_LCM = "UR_PLM_STAGE_STAGE_LCM",
  UR_PLM_STAGE_BI_STAGE_LCM = "UR_PLM_STAGE_BI_STAGE_LCM",
  UR_PLM_STAGE_LEVEL_ONE_EC = "UR_PLM_STAGE_LEVEL_ONE_EC",
  UR_PLM_STAGE_LEVEL_TWO_EC = "UR_PLM_STAGE_LEVEL_TWO_EC",
  UR_PLM_STAGE_TDP_EC = "UR_PLM_STAGE_TDP_EC",
  UR_PLM_STAGE_LEVEL_FOUR_EC = "UR_PLM_STAGE_LEVEL_FOUR_EC",
  UR_PLM_STAGE_BIB_PLANNING_NAME = "UR_PLM_STAGE_BIB_PLANNING_NAME",
  UR_PLM_STAGE_BIB_NBR_SOCKETS = "UR_PLM_STAGE_BIB_NBR_SOCKETS",
  UR_PLM_STAGE_INITIAL_DURATION = "UR_PLM_STAGE_INITIAL_DURATION",
  UR_PLM_STAGE_BI_DURATION = "UR_PLM_STAGE_BI_DURATION",
  UR_PLM_STAGE_BIC_ADJUSTMENT_FACTOR = "UR_PLM_STAGE_BIC_ADJUSTMENT_FACTOR",
  UR_PLM_STAGE_BIC_AVAILABILITY = "UR_PLM_STAGE_BIC_AVAILABILITY",
  UR_PLM_STAGE_BIC_USAGE_RATE = "UR_PLM_STAGE_BIC_USAGE_RATE",
  UR_PLM_STAGE_BIB_USAGE_RATE = "UR_PLM_STAGE_BIB_USAGE_RATE",
  UR_PLM_STAGE_MULTISITE = "UR_PLM_STAGE_MULTISITE",
  UR_PLM_STAGE_PGDW = "UR_PLM_STAGE_PGDW",
  UR_PLM_STAGE_INITIAL_TEST_TIME = "UR_PLM_STAGE_INITIAL_TEST_TIME",
  UR_PLM_STAGE_TEST_TIME = "UR_PLM_STAGE_TEST_TIME",
  UR_PLM_STAGE_PP = "UR_PLM_STAGE_PP",
  UR_PLM_STAGE_AVAILABILITY = "UR_PLM_STAGE_AVAILABILITY",
  UR_PLM_STAGE_LOAD_TIME = "UR_PLM_STAGE_LOAD_TIME",
  UR_PLM_STAGE_INDEX_TIME = "UR_PLM_STAGE_INDEX_TIME",
  UR_PLM_STAGE_USAGE_RATE = "UR_PLM_STAGE_USAGE_RATE",
  UR_PLM_STAGE_STEP_YIELD = "UR_PLM_STAGE_STEP_YIELD",
  UR_PLM_STAGE_CUM_INPUT_YIELD = "UR_PLM_STAGE_CUM_INPUT_YIELD",
  UR_PLM_STAGE_CUM_OUTPUT_YIELD = "UR_PLM_STAGE_CUM_OUTPUT_YIELD",
  UR_PLM_STAGE_ADJ_USAGE_RATE = "UR_PLM_STAGE_ADJ_USAGE_RATE",
  UR_PLM_STAGE_STEP_NAME = "UR_PLM_STAGE_STEP_NAME",
  UR_PLM_STAGE_OPERATION_UTILIZATION = "UR_PLM_STAGE_OPERATION_UTILIZATION",
  UR_PLM_STAGE_LLC_RG = "UR_PLM_STAGE_LLC_RG",
  UR_PLM_STAGE_PKUT = "UR_PLM_STAGE_PKUT",
  UR_PLM_STAGE_POV_EFFICIENCY = "UR_PLM_STAGE_POV_EFFICIENCY",

  EMPTY = "EMPTY",

  STEP_MAPPING_SITE = "STEP_MAPPING_SITE",
  STEP_MAPPING_MFG_STEP = "STEP_MAPPING_MFG_STEP",
  STEP_MAPPING_STEP_TYPE = "STEP_MAPPING_STEP_TYPE",
  STEP_MAPPING_LAST_UPDATED = "STEP_MAPPING_LAST_UPDATED",
  STEP_MAPPING_UPDATED_BY = "STEP_MAPPING_UPDATED_BY",

  /**
   * Usage Rate Packing Flow Overview
   */
  UR_PACKINGFLOW_SAP_CODE = "UR_PACKINGFLOW_SAP_CODE",
  UR_PACKINGFLOW_PART_12NC = "UR_PACKINGFLOW_PART_12NC",
  UR_PACKINGFLOW_PART_DESCRIPTION = "UR_PACKINGFLOW_PART_DESCRIPTION",
  UR_PACKINGFLOW_PART_TYPE = "UR_PACKINGFLOW_PART_TYPE",
  UR_PACKINGFLOW_PART_MATURITY = "UR_PACKINGFLOW_PART_MATURITY",
  UR_PACKINGFLOW_MAG = "UR_PACKINGFLOW_MAG",
  UR_PACKINGFLOW_PACKAGE_TYPE_DESCRIPTION = "UR_PACKINGFLOW_PACKAGE_TYPE_DESCRIPTION",
  UR_PACKINGFLOW_ASSEMBLY_CG = "UR_PACKINGFLOW_ASSEMBLY_CG",
  UR_PACKINGFLOW_PKG_OUTLINE_VERSION_DESC = "UR_PACKINGFLOW_PKG_OUTLINE_VERSION_DESC",
  UR_PACKINGFLOW_PKG_OUTLINE_VERSION_LEGACY_PART = "UR_PACKINGFLOW_PKG_OUTLINE_VERSION_LEGACY_PART",
  UR_PACKINGFLOW_DRY_PACK = "UR_PACKINGFLOW_DRY_PACK",
  UR_PACKINGFLOW_PACKING_TYPE = "UR_PACKINGFLOW_PACKING_TYPE",
  UR_PACKINGFLOW_PACKING_BODY_WIDTH = "UR_PACKINGFLOW_PACKING_BODY_WIDTH",
  UR_PACKINGFLOW_PACKING_BODY_LENGTH = "UR_PACKINGFLOW_PACKING_BODY_LENGTH",
  UR_PACKINGFLOW_PACKING_BODY_HEIGHT = "UR_PACKINGFLOW_PACKING_BODY_HEIGHT",
  UR_PACKINGFLOW_PACKING_METHOD = "UR_PACKINGFLOW_PACKING_METHOD",
  UR_PACKINGFLOW_PACKING_METHOD_DESCRIPTION = "UR_PACKINGFLOW_PACKING_METHOD_DESCRIPTION",
  UR_PACKINGFLOW_PACKING_QUANTITY = "UR_PACKINGFLOW_PACKING_QUANTITY",
  UR_PACKINGFLOW_MFG_STAGE = "UR_PACKINGFLOW_MFG_STAGE",
  UR_PACKINGFLOW_PACKING_FLOW_ID = "UR_PACKINGFLOW_PACKING_FLOW_ID",
  UR_PACKINGFLOW_PACKING_FLOW_NAME = "UR_PACKINGFLOW_PACKING_FLOW_NAME",
  UR_PACKINGFLOW_PACKING_FLOW_MATURITY = "UR_PACKINGFLOW_PACKING_FLOW_MATURITY",
  UR_PACKINGFLOW_PLANNING = "UR_PACKINGFLOW_PLANNING",
  UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_NAME = "UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_NAME",
  UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_ACTIVATION = "UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_ACTIVATION",
  UR_PACKINGFLOW_FLOW_PRIORITY = "UR_PACKINGFLOW_FLOW_PRIORITY",
  UR_PACKINGFLOW_STEP_SEQUENCE = "UR_PACKINGFLOW_STEP_SEQUENCE",
  UR_PACKINGFLOW_STEP_TYPE = "UR_PACKINGFLOW_STEP_TYPE",
  UR_PACKINGFLOW_STEP_INDICATOR_CATEGORY = "UR_PACKINGFLOW_STEP_INDICATOR_CATEGORY",
  UR_PACKINGFLOW_PACKAGE_TYPE_FAMILY_NAME = "UR_PACKINGFLOW_PACKAGE_TYPE_FAMILY_NAME",
  UR_PACKINGFLOW_EQUIPMENT_TYPE = "UR_PACKINGFLOW_EQUIPMENT_TYPE",
  UR_PACKINGFLOW_L1_EC = "UR_PACKINGFLOW_L1_EC",
  UR_PACKINGFLOW_L1_EC_NAME = "UR_PACKINGFLOW_L1_EC_NAME",
  UR_PACKINGFLOW_L1_RG = "UR_PACKINGFLOW_L1_RG",
  UR_PACKINGFLOW_L1_RG_NAME = "UR_PACKINGFLOW_L1_RG_NAME",
  UR_PACKINGFLOW_LLC_RG = "UR_PACKINGFLOW_LLC_RG",
  UR_PACKINGFLOW_EFFECTIVE_DATE_USAGE_RATE = "UR_PACKINGFLOW_EFFECTIVE_DATE_USAGE_RATE",
  UR_PACKINGFLOW_OPERATION_UTILIZATION = "UR_PACKINGFLOW_OPERATION_UTILIZATION",
  UR_PACKINGFLOW_POV_EFFICIENCY = "UR_PACKINGFLOW_POV_EFFICIENCY",
  UR_PACKINGFLOW_YIELD = "UR_PACKINGFLOW_YIELD",
  UR_PACKINGFLOW_PK_UNIT_TIME = "UR_PACKINGFLOW_PK_UNIT_TIME",
  UR_PACKINGFLOW_IDEAL_UNIT_PER_HOUR = "UR_PACKINGFLOW_IDEAL_UNIT_PER_HOUR",
  UR_PACKINGFLOW_USAGE_RATE = "UR_PACKINGFLOW_USAGE_RATE",
  UR_PACKINGFLOW_UNIT_PER_DAY = "UR_PACKINGFLOW_UNIT_PER_DAY",
  UR_PACKINGFLOW_NET_UNIT_PER_HOUR = "UR_PACKINGFLOW_NET_UNIT_PER_HOUR",
  UR_PACKINGFLOW_USAGE_RATE_FINANCIAL = "UR_PACKINGFLOW_USAGE_RATE_FINANCIAL",
  UR_PACKINGFLOW_FINANCIAL_PLANNING_FLAG = "UR_PACKINGFLOW_FINANCIAL_PLANNING_FLAG",
  UR_PACKINGFLOW_LAST_UPDATED = "UR_PACKINGFLOW_LAST_UPDATED",
  UR_PACKINGFLOW_PRODUCED = "UR_PACKINGFLOW_PRODUCED",
  UR_PACKINGFLOW_MAN_MACHINE_RATIO = "UR_PACKINGFLOW_MAN_MACHINE_RATIO",
  UR_PACKINGFLOW_PCA_RESOURCE = "UR_PACKINGFLOW_PCA_RESOURCE",
  UR_PACKINGFLOW_PACKING_STEP_ID = "UR_PACKINGFLOW_PACKING_STEP_ID",
  UR_PACKINGFLOW_PACKING_STEP_NAME = "UR_PACKINGFLOW_PACKING_STEP_NAME",
  UR_PACKINGFLOW_PACKING_STEP_MATURITY = "UR_PACKINGFLOW_PACKING_STEP_MATURITY",
  UR_PACKINGFLOW_PACKING_STAGE_ID = "UR_PACKINGFLOW_PACKING_STAGE_ID",
  UR_PACKINGFLOW_PACKING_STAGE_NAME = "UR_PACKINGFLOW_PACKING_STAGE_NAME",
  UR_PACKINGFLOW_PACKING_STAGE_MATURITY = "UR_PACKINGFLOW_PACKING_STAGE_MATURITY",
  UR_PACKINGFLOW_INFO_TYPE = "UR_PACKINGFLOW_INFO_TYPE",
  UR_PACKINGFLOW_MFG_WORKFLOW = "UR_PACKINGFLOW_MFG_WORKFLOW",
}

export class EmitSortChange {
  public field: GenericSearchSortField;
  public direction: SortDirection;

  public constructor(field: GenericSearchSortField, direction: SortDirection) {
    this.field = field;
    this.direction = direction;
  }
}

export enum GenericSearchType {
  EMPTY = "EMPTY",
  DEFAULT = "DEFAULT",
  DATE_FROM_TO = "DATE_FROM_TO",
  NUM_FROM_TO = "NUM_FROM_TO",
  DROPDOWN_SINGLE = "DROPDOWN_SINGLE", // dropdown single-select
  DROPDOWN_MULTI = "DROPDOWN_MULTI", // multi-select
}

export const SEARCH_MIN_VALUE = "-10000000";
export const SEARCH_MAX_VALUE = "10000000";
export const SEARCH_MIN_DATE = "1999-01-01";
export const SEARCH_MAX_DATE = "2999-01-01";

@Injectable()
export class GenericSearchUtils {
  public fromToDates = [
    GenericSearchSortField.E_LAST_UPDATED,
    GenericSearchSortField.EVENT_START_DATE,
    GenericSearchSortField.EVENT_END_DATE,
    GenericSearchSortField.EC_P_AVAILABILITY_LASTUPDATED,
    GenericSearchSortField.EC_LAST_UPDATED,
    GenericSearchSortField.RG_LAST_UPDATE,
    GenericSearchSortField.RC_LASTUPDATED,
    GenericSearchSortField.LOC_LASTUPDATED,
    GenericSearchSortField.NOTIFICATION_TIMESTAMP,
    GenericSearchSortField.REQUEST_SUBMITDATE,
    GenericSearchSortField.APPROVAL_SUBMITDATE,
    GenericSearchSortField.APPROVAL_MANAGEMENT_LASTUPDATED,
    GenericSearchSortField.UR_ACTIVATION_FLOW_OVERVIEW_ACTIVATION_DATE,
    GenericSearchSortField.UR_ISSUE_LASTUPDATED,
    GenericSearchSortField.EC_P_AVAILABILITY_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_INDEXTIME_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_INDEXTIME_LASTUPDATED,
    GenericSearchSortField.EC_P_LOADTIME_LASTUPDATED,
    GenericSearchSortField.EC_P_LOADTIME_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_MANMACHINERATIO_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_MANMACHINERATIO_LASTUPDATED,
    GenericSearchSortField.TDP_INSERT_DATE,
    GenericSearchSortField.TDP_LAST_UPDATED,
    GenericSearchSortField.UR_TESTFLOW_IEMDM_PLANNING_FLOW_ACTIVATION,
    GenericSearchSortField.UR_TESTFLOW_EFFECTIVE_DATE_USAGERATE,
    GenericSearchSortField.UR_TESTFLOW_LASTUPDATED,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_LAST_UPDATED,
    GenericSearchSortField.EC_P_BURN_IN_CHAMBER_SLOTS_LASTUPDATED,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_LASTUPDATED,
    GenericSearchSortField.BURN_IN_BOARD_LAST_UPDATED,
    GenericSearchSortField.EC_P_OPERATION_UTILIZATION_LASTUPDATED,
    GenericSearchSortField.EC_P_OPERATION_UTILIZATION_EFFECTIVEDATE,
    GenericSearchSortField.EC_P_RESOURCE_SECONDARY_LASTUPDATED,
    GenericSearchSortField.STEP_MAPPING_LAST_UPDATED,
    GenericSearchSortField.PK_POV_PARAMS_LAST_UPDATED,
    GenericSearchSortField.PK_POV_EFFICIENCY_LAST_UPDATED,
    GenericSearchSortField.PK_MANUAL_FLOW_LAST_UPDATED,
    GenericSearchSortField.UR_PACKINGFLOW_IEMDM_PLANNING_FLOW_ACTIVATION,
    GenericSearchSortField.UR_PACKINGFLOW_EFFECTIVE_DATE_USAGE_RATE,
    GenericSearchSortField.UR_PACKINGFLOW_LAST_UPDATED,
    GenericSearchSortField.MISSING_LINK_LAST_UPDATED,
  ];

  public fromToNums = [
    GenericSearchSortField.P_COMM_YIELD,
    GenericSearchSortField.EVENT_AMOUNT,
    GenericSearchSortField.EC_P_AVAILABILITY_VALUE,
    GenericSearchSortField.EC_P_INDEXTIME_VALUE,
    GenericSearchSortField.EC_P_INDEXTIME_MULTISITE,
    GenericSearchSortField.EC_P_LOADTIME_VALUE,
    GenericSearchSortField.EC_P_MANMACHINERATIO_VALUE,
    GenericSearchSortField.UR_TESTFLOW_PRIORITY,
    GenericSearchSortField.UR_TESTFLOW_STEP_SEQUENCE,
    GenericSearchSortField.UR_TESTFLOW_TEMPRATURE,
    GenericSearchSortField.UR_TESTFLOW_MULTISITE,
    GenericSearchSortField.UR_TESTFLOW_INITIAL_TEST_TIME,
    GenericSearchSortField.UR_TESTFLOW_TEST_TIME,
    GenericSearchSortField.UR_TESTFLOW_AVAILABILITY,
    GenericSearchSortField.UR_TESTFLOW_LOADTIME,
    GenericSearchSortField.UR_TESTFLOW_INDEXTIME,
    GenericSearchSortField.UR_TESTFLOW_PRODUCT_PERFORMANCE,
    GenericSearchSortField.UR_TESTFLOW_USAGERATE,
    GenericSearchSortField.UR_TESTFLOW_USAGERATE_FINANCIAL,
    GenericSearchSortField.EC_P_BURN_IN_CHAMBER_SLOTS,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_TIME_BETWEEN_TURNS,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_RE_BURN_IN_RATE,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_SOCKET_DENSITY,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_SOCKET_UTILIZATION,
    GenericSearchSortField.EC_P_BURN_IN_BOARD_CHAMBER_ADJUSTMENT_FACTOR,
    GenericSearchSortField.BURN_IN_BOARD_NUMBER_OF_SOCKETS,
    GenericSearchSortField.EC_P_OPERATION_UTILIZATION_VALUE,
    GenericSearchSortField.PK_POV_PARAMS_STEP_SEQUENCE,
    GenericSearchSortField.PK_POV_PARAMS_PQ,
    GenericSearchSortField.PK_POV_PARAMS_PKUT,
    GenericSearchSortField.PK_POV_PARAMS_PRIORITY,
    GenericSearchSortField.PK_POV_EFFICIENCY_PRODUCED,
    GenericSearchSortField.PK_POV_EFFICIENCY_EFFICIENCY,
    GenericSearchSortField.UR_PACKINGFLOW_PACKING_QUANTITY,
    GenericSearchSortField.UR_PACKINGFLOW_FLOW_PRIORITY,
    GenericSearchSortField.UR_PACKINGFLOW_STEP_SEQUENCE,
    GenericSearchSortField.UR_PACKINGFLOW_OPERATION_UTILIZATION,
    GenericSearchSortField.UR_PACKINGFLOW_POV_EFFICIENCY,
    GenericSearchSortField.UR_PACKINGFLOW_PK_UNIT_TIME,
    GenericSearchSortField.UR_PACKINGFLOW_IDEAL_UNIT_PER_HOUR,
    GenericSearchSortField.UR_PACKINGFLOW_USAGE_RATE,
    GenericSearchSortField.UR_PACKINGFLOW_UNIT_PER_DAY,
    GenericSearchSortField.UR_PACKINGFLOW_NET_UNIT_PER_HOUR,
    GenericSearchSortField.UR_PACKINGFLOW_USAGE_RATE_FINANCIAL,
    GenericSearchSortField.UR_PACKINGFLOW_PRODUCED,
    GenericSearchSortField.UR_PACKINGFLOW_MAN_MACHINE_RATIO,
  ];

  public dropDownSingles = [
    GenericSearchSortField.P_EXCLUDE_DATE_EXISTS,
    GenericSearchSortField.E_SKELETON,
    GenericSearchSortField.LOC_SUBCON,
    GenericSearchSortField.TDP_PLANNING_FLAG,
    GenericSearchSortField.UR_TESTFLOW_FINANCIAL_PLANNING_FLAG,
    GenericSearchSortField.BURN_IN_BOARD_PLANNING_FLAG,
  ];

  public dropDownMultis = [
    GenericSearchSortField.EVENT_STATUS,
    GenericSearchSortField.RG_STATUS,
    GenericSearchSortField.EVENT_TYPE,
    GenericSearchSortField.EVENT_DEDICATION,
    GenericSearchSortField.UR_ISSUE_TYPE,
    GenericSearchSortField.EC_STATUS,
    GenericSearchSortField.E_STATUS,
    GenericSearchSortField.UR_PLM_STAGE_STEP_TYPE,
    GenericSearchSortField.P_BURN_IN_MARKER,
    GenericSearchSortField.P_MFGSTAGE,
    GenericSearchSortField.P_LCM,
    GenericSearchSortField.PV_STATUS,
    GenericSearchSortField.UR_ACTIVATION_FLOW_OVERVIEW_FLOW_TYPE,
    GenericSearchSortField.MISSING_LINK_STATUS,
  ];

  public disabled = [GenericSearchSortField.EVENT_COMPLETED];

  public du = new DateUtils();
  private genericSearchNameToFieldMap: Record<string, string> = {};
  private usernames: Record<string, string> = {};

  public constructor(private store: Store) {
    this.store
      .select(SystemSelectors.selectGenericSearchMap)
      .subscribe((value) => (this.genericSearchNameToFieldMap = value));

    this.store
      .select(SystemSelectors.selectUserNames)
      .subscribe((value) => (this.usernames = value));
  }

  public getSearchType(fld: GenericSearchSortField): GenericSearchType {
    if (this.fromToNums.indexOf(fld) > -1) {
      return GenericSearchType.NUM_FROM_TO;
    } else if (this.fromToDates.indexOf(fld) > -1) {
      return GenericSearchType.DATE_FROM_TO;
    } else if (this.dropDownSingles.indexOf(fld) > -1) {
      return GenericSearchType.DROPDOWN_SINGLE;
    } else if (this.dropDownMultis.indexOf(fld) > -1) {
      return GenericSearchType.DROPDOWN_MULTI;
    } else if (fld === GenericSearchSortField.EMPTY) {
      return GenericSearchType.EMPTY;
    } else {
      return GenericSearchType.DEFAULT;
    }
  }

  // return TRUE if (case-insensitive) search value is like property value or the corresponding search arg is not set.
  public isLike(
    value: string,
    searchArguments: GenericSearchArguments,
    field: GenericSearchSortField
  ): boolean {
    const searchArg = searchArguments.getSearchField(field);
    return this.isActualLikeSearchValue(value, searchArg?.value);
  }

  public isActualLikeSearchValue(
    actualValue: string,
    searchValue: string
  ): boolean {
    if (searchValue && actualValue) {
      return actualValue.toLowerCase().indexOf(searchValue.toLowerCase()) > -1;
    }

    return !(searchValue && !actualValue);
  }

  // return TRUE if (case-insensitive) search values contain property value or the corresponding search arg is not set.
  public isLikeMultiple(
    compareToValue: string | boolean,
    searchArguments: GenericSearchArguments,
    field: GenericSearchSortField
  ): boolean {
    const searchArg = searchArguments.getSearchField(field);
    if (searchArg && searchArg.value) {
      const split = searchArg.value.split(";");
      // In this case, when searchValue is falsy, it means a check box for null data was checked in the UI, so return true only in case the
      // actual value (compareToValue) is also falsy, otherwise apply the logic from isActualLikeSearchValue, which would normally return
      // true in this special case.
      return split.some((searchValue: string) =>
        !searchValue
          ? !compareToValue
          : this.isActualLikeSearchValue(compareToValue as string, searchValue)
      );
    } else {
      return true; // the corresponding search arg is not set.
    }
  }

  // return TRUE if (case-insensitive) search person name is like property value or the corresponding search arg is not set.
  public isPersonLike(
    person: Person,
    searchArguments: GenericSearchArguments,
    field: GenericSearchSortField
  ): boolean {
    const searchArg = searchArguments.getSearchField(field);
    if (searchArg && person) {
      return (
        person.name.toLowerCase().indexOf(searchArg.value.toLowerCase()) > -1
      );
    } else {
      return true; // the corresponding search arg is not set.
    }
  }

  // return TRUE if search value is between property value or the corr search arg is not set.
  public isBetween(
    value: boolean | Date | string | number | null | undefined,
    searchArguments: GenericSearchArguments,
    field: GenericSearchSortField
  ): boolean {
    if (!value || typeof value === "boolean") {
      return false;
    }

    const searchArg = searchArguments.getSearchField(field);
    const searchType = this.getSearchType(field);

    if (searchArg && searchArg.value.trim().length > 0) {
      const items = (searchArg.value + ";").split(";");
      if (searchType == GenericSearchType.DATE_FROM_TO) {
        const date = this.du.toDate(value);
        const fromDate = this.du.toDate(items[0]);
        const toDate = this.du.toDate(items[1]);
        return (
          this.du.isSameOrAfter(date, fromDate) &&
          this.du.isSameOrBefore(date, toDate)
        );
      } else {
        const fromVal = items[0];
        const toVal = items[1];
        return value >= fromVal && value <= toVal;
      }
    } else {
      return true; // the corr search arg is not set.
    }
  }

  public isLikeUsername(
    value: string,
    searchArguments: GenericSearchArguments,
    field: GenericSearchSortField
  ): boolean {
    const searchArg = searchArguments.getSearchField(field);

    if (searchArg && searchArg.value && searchArg.value.length > 0) {
      const lookFor = searchArg.value.toLowerCase();

      for (const key of Object.keys(this.usernames)) {
        const name = this.usernames[key]?.toLowerCase() ?? "";
        if (name.indexOf(lookFor) > -1) {
          if (key === value) {
            return true;
          }
        }
      }

      return false;
    } else {
      return true;
    }
  }

  public getFieldByName(name: string): string {
    return this.genericSearchNameToFieldMap[name];
  }

  public sortData(
    fieldName: string,
    direction: string,
    searchArguments: GenericSearchArguments
  ): boolean {
    const sortField = this.getFieldByName(
      fieldName
    ) as keyof typeof GenericSearchSortField;
    if (sortField) {
      if (direction.trim().length > 0) {
        const sortArg = new GenericSortArg(
          GenericSearchSortField[sortField],
          direction.toLowerCase() == "desc"
        );

        // get the current sort args without the current selected
        const currSortArgs: Array<GenericSortArg> = [];
        searchArguments.sortArgs.forEach((e) => {
          if (e.field !== sortField) {
            currSortArgs.push(e);
          }
        });

        // and build a list with the selected at the top plus the others
        searchArguments.sortArgs = [];
        searchArguments.sortArgs.push(sortArg);
        let idx = 0;
        currSortArgs.forEach((e) => {
          if (idx++ < 5) {
            searchArguments.sortArgs.push(e);
          } // todo max 5
        });
      } else {
        searchArguments.sortArgs = searchArguments.sortArgs.filter(
          (arg) => arg.field !== sortField
        );
      }
      return true;
    } else {
      console.log("No sort field found for " + fieldName);
      return false;
    }
  }
}
