export class Update {
  updatedType?: UpdateType;
  locationId = 0;
  updateData: any;
  userWbi = "";
}

export enum UpdateType {
  PERSON = "PERSON",
  USERROLE = "USERROLE",
  LOCATION = "LOCATION",
  EQUIPMENT = "EQUIPMENT",
  RESOURCEGROUP = "RESOURCEGROUP",
  RESOURCECLASS = "RESOURCECLASS",
  EQUIPMENTCODE = "EQUIPMENTCODE",
  SAPCODE = "SAPCODE",
  PLANNING = "PLANNING",
  PROCESS_STAGE = "PROCESS_STAGE",
  PART_12NC = "PART_12NC",
  PLANNING_FLAG = "PLANNING_FLAG",
  CONFIG_VALUE_ITEM = "CONFIG_VALUE_ITEM",
  IEMDM_ALERT = "IEMDM_ALERT",
  APPROVAL = "APPROVAL",
  USER_ALERT = "USER_ALERT",
  SCHEDULED_TRIGGER = "SCHEDULED_TRIGGER",
  MASS_UPLOAD_PROGRESS = "MASS_UPLOAD_PROGRESS",
  STEP_MAPPING = "STEP_MAPPING",
  STEP_TYPE = "STEP_TYPE",
  POV_EFFICIENCY = "POV_EFFICIENCY",
  POV_PARAMS = "POV_PARAMS",
  MANUAL_FLOW = "MANUAL_FLOW",
  MISSING_LINK = "MISSING_LINK",
}
