package com.nxp.iemdm.model.notification;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.nxp.iemdm.model.user.Person;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import java.io.Serializable;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@MappedSuperclass
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = Notification.class, name = "notification"),
})
@XmlAccessorType(XmlAccessType.FIELD)
public abstract class NotificationParent implements Serializable, Comparable<NotificationParent> {
  public static final int MESSAGE_MAX_SIZE = 4000;
  // Keep some safety margin to avoid Unicode characters occupying 2 or more chars in Java.
  public static final int MESSAGE_SAFE_SIZE = 3990;

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "ID")
  private Integer id;

  @ManyToOne
  @JoinColumn(name = "USER_ID", referencedColumnName = "WBI", nullable = false)
  @NotNull
  private Person recipient;

  @Size(max = MESSAGE_MAX_SIZE)
  @Column(name = "MESSAGE", length = MESSAGE_MAX_SIZE)
  private String message;

  @Column(name = "TIMESTAMP")
  private Instant timestamp;

  @Column(name = "READ")
  private boolean read;

  public abstract String getType();

  /**
   * Ensures the message is no longer than {@value #MESSAGE_SAFE_SIZE} Unicode units by trimming it
   * and appending an ellipsis to signal it has been trimmed.
   *
   * <p>The current classes extending {@link NotificationParent} contain messages generated by the
   * application. These are not supposed to reach the maximum length, but if they would, they may
   * just be trimmed to fit the size constraint.<br>
   * A validation exception would not be desirable in this case as the notifications themselves
   * should not be suppressed. Presenting a trimmed down version of the message that will fit in the
   * database column is the chosen approach.
   */
  @PrePersist
  @PreUpdate
  void ensureMessageIsNotTooLarge() {
    if (this.message == null || this.message.length() <= MESSAGE_SAFE_SIZE) {
      return;
    }

    final String ellipsis = "...";
    this.message = this.message.substring(0, MESSAGE_SAFE_SIZE - ellipsis.length()) + ellipsis;
  }

  @Override
  public int compareTo(NotificationParent notification) {
    return notification.getTimestamp().compareTo(this.timestamp);
  }
}
